const express = require('express')
const mongoose = require('mongoose')
const bodyParser = require('body-parser')
const passport = require('passport')
const authRoutes = require('./routes/auth')
const infoRoute = require('./routes/info')
const latencyRoute = require('./routes/latency')
const logoutRoute = require('./routes/logout')
const db = require('./config/db')
const app = express()

mongoose.connect(db.MONGO_URI, { useNewUrlParser: true, useCreateIndex: true, useUnifiedTopology: true })
  .then(() => console.log('MongoDB connected!'))
  .catch(error => console.log(error))

app.use(passport.initialize())
require('./Utils/passport')(passport)
app.use(require('morgan')('dev'))
app.use(require('cors')())
app.use(bodyParser.urlencoded({extended: true}))
app.use(bodyParser.json())
app.use('/api/auth', authRoutes)
app.use('/api', infoRoute)
app.use('/api', logoutRoute)
app.use('/api', latencyRoute)
module.exports = app